// Package models defines essential struct or interface
package models

import (
	"time"
)

// Event struct define for
type Event struct {
	// ID is the distinct identity for this event
	ID int

	// Title contains a few words describe this event
	Title string

	// Summary
	Summary string

	// OccurTime record when this event happened
	OccurTime time.Time

	// CreateTime is auto generated by database
	// It record when this event is inserted into database
	CreateTime time.Time

	// The format of source
	Format FormatType

	// Source contains comprehensive content about this event
	// It should be objective. You can add some links for repository or pictures
	Source string

	// WARN: You should not use this structure
	// Because it this is enabled, different plugins may not work independently
	// attributes store data
	// plugins can store processed data there
	// Attributes map[string]any
}
