id = "2a45a6184b2adefd"
title = "Design SQL Table"
energy = 1
work_status = 2
context_path = "/home/cai/WORK/project/decision_analyst/.project-todo/context/2a45a6184b2adefd-Design SQL Table.md"
viewer = 0
create_time = 2026-09-28T14:59:52.536799147+08:00
start_time = 2026-09-28T17:28:28.583119658+08:00
end_time = 2026-09-28T17:28:49.257180734+08:00
blocked_works_id = []
blocked_times = 0
@@@@@GAP@@@@@
id = "4ff7413c8cd818a5"
title = "Write a minimal Web demo"
energy = 2
work_status = 2
context_path = "/home/cai/WORK/project/decision_analyst/.project-todo/context/4ff7413c8cd818a5-Write a minimal Web demo.md"
viewer = 0
create_time = 2026-09-28T20:14:07.210770387+08:00
start_time = 2026-09-28T20:41:53.034059222+08:00
end_time = 2026-09-28T20:42:02.635556396+08:00
blocked_works_id = []
blocked_times = 0
@@@@@GAP@@@@@
