id = "2a45a6184b2adefd"
title = "Design SQL Table"
energy = 1
work_status = 0
context_path = "/home/cai/WORK/project/decision_analyst/.project-todo/context/2a45a6184b2adefd-Design SQL Table.md"
viewer = 0
create_time = 2026-09-28T14:59:52.536799147+08:00
start_time = 2026-09-28T14:59:52.536799147+08:00
end_time = 2026-09-28T14:59:52.536799147+08:00
blocked_works_id = []
blocked_times = 0
@@@@@GAP@@@@@
